census_data_url: http://censusdata.ire.org/SS/all_LLL_in_SS.TT.csv
download_dir: /users/nslater/data/census
s3_bucket: swf-census-data
task_list: swf-census-data
domain: swf-census-data
activities:
  download_data_file:
    version: 1.0.3
    start_timeout: 30
    close_timeout: 30
    task_list: swf-census-data
  copy_file_to_s3:
    version: 1.0.5
    start_timeout: 30
    close_timeout: 30
    task_list: swf-census-data
decider:
  version: 1.0.3
  timeout: 3600


