census_data_url: http://censusdata.ire.org/SS/all_LLL_in_SS.TT.csv
download_dir: /users/nslater/data/census
s3_bucket: swf-census-data
task_list: swf-census-data
domain: swf-census-data
activities:
  download_data_file:
    version: 1.0.4
    start_timeout: 3600
    close_timeout: 3600
    task_list: swf-census-data
  copy_file_to_s3:
    version: 1.0.12
    start_timeout: 3600
    close_timeout: 3600
    task_list: swf-census-data
decider:
  version: 1.0.4
  timeout: 86400


